
name: CD - Deploy to GKE

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}
        export_default_credentials: true

    - name: Authenticate Docker with Artifact Registry
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > ${HOME}/gcp-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Verify authentication
      run: |
        gcloud auth list
        gcloud config list
        gcloud auth print-access-token | head -c 20 && echo "..."

    - name: Build and push Docker image
      run: |
        docker build -t iris-api .
        docker tag iris-api us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-repo/iris-api:latest
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-repo/iris-api:latest

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials demo-gke-iris-cluster2 --zone us-central1-a --project ${{ secrets.GCP_PROJECT }}

    - name: Deploy to GKE
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
